### PR TITLE
Add node `16.6.0` to workflow bcoz u seems krazy

### PR DESCRIPTION
**Pull request by BlobHuman**

### CODE REVIEW

**Comment by GhexterCortes** [comment]
nub

**Comment by BlobHuman** [comment]
bruh this is cancelled

**Comment by GhexterCortes** [comment]
offtopic: can i trust u to code my server's automatic role managements bot? It was named HiddenPlayer based on axis 1.4.4

**Comment by BlobHuman** [comment]
> offtopic: can i trust u to code my server's automatic role managements bot? It was named HiddenPlayer based on axis 1.4.4

no and wth that's an ancient version you're now developing 1.6.0 but haven't updated your own bot?

**Comment by GhexterCortes** [comment]
> > offtopic: can i trust u to code my server's automatic role managements bot? It was named HiddenPlayer based on axis 1.4.4
> 
> no and wth that's an ancient version you're now developing 1.6.0 but haven't updated your own bot?

im lazy to update but fr im serious

**Comment by BlobHuman** [comment]
> > > offtopic: can i trust u to code my server's automatic role managements bot? It was named HiddenPlayer based on axis 1.4.4
> > 
> > 
> > no and wth that's an ancient version you're now developing 1.6.0 but haven't updated your own bot?
> 
> im lazy to update but fr im serious

sure bcoz you're abt to cry

**Comment by GhexterCortes** [comment]
sas

**Pull request merged**
